spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://43.201.37.133:3306/DB202011956?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=utf8"
    username: user202011956
    password: "!mynameis202011956"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show_sql: true
